config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  post 'filter_source', to: 'home#filter_source'
  post 'tagging', to: 'home#tagging'
  post 'add_domains_form', to: 'home#add_domains_form'
  get 'report', to: 'home#report'
  get 'add_domains', to: 'home#add_domains'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current_state.rb
class CurrentState < ApplicationRecord
  enum filter_type: [:new_domains, :all_domains]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include HomeHelper
  http_basic_authenticate_with name: ENV['http_username'],
                               password: ENV['http_password'],
                               only: :index

  def index
    @segments = ['Sports', 'Gaming ', 'Outdoor', 'Fitness', 'Comedy', 'Special Interest', 'Faith', 'News & Politics', 'Personality', 'Lifestyle', 'Kids & Family', 'Music', 'TV & Film', 'Education', 'Subscription Commerce', 'Corporate', 'Events', 'Agency', 'Other']
    @content_types = ['Episodic', 'Long form', 'Short form', 'Broadcast (linear)', 'Live streaming (event based)', 'Audio (podcast)']

    unless set_bq_vars
      @sources = []
      flash[:alert] = "Can't find any table in dataset" if ENV['manual_table'].blank?
      flash[:alert] = "Can't find dataset" if ENV['manual_dataset'].blank?
      return
    end

    @output_error = ''

    sql = "SELECT DISTINCT Source FROM #{@table}"
    @sources = @bigquery.query(sql).map { |s|  s[:Source] }
    session[:sources] = @sources

    current = CurrentState.first_or_create

    filter_type_query = current.filter_type == 'new_domains' ? "Reviewed_Date IS NULL" : "1=1"
    filter_source_query = current.filter_source.present? ? "Source = '#{current.filter_source}'" : "1=1"

    sql = "SELECT COUNT(*) FROM #{@table} WHERE #{filter_type_query} AND #{filter_source_query}"
    total_count = @bigquery.query(sql).first.values.first

    if current.domain.present?
      sql = "WITH Cte AS (SELECT *, ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS number FROM #{@table} WHERE #{filter_type_query} AND #{filter_source_query}) SELECT * FROM Cte WHERE Company_Domain = '#{current.domain}'"
      cur_row = @bigquery.query(sql).first

      if cur_row
        cur_row_number = cur_row[:number]
      else
        sql = "SELECT * FROM #{@table} LIMIT 1"
        cur_row = @bigquery.query(sql).first
        cur_row_number = 1
        current.update_attributes(domain: cur_row[:Company_Domain])
      end
    else
      sql = "SELECT * FROM #{@table} WHERE #{filter_type_query} AND #{filter_source_query} LIMIT 1"
      cur_row = @bigquery.query(sql).first
      cur_row_number = 1
      current.update_attributes(domain: cur_row[:Company_Domain])
    end

    @domain = current&.domain
    @source = cur_row[:Source]
    @filter_type = current&.filter_type || :new_domains
    @filter_source = current&.filter_source

    @sites_left = total_count - cur_row_number
    @segment = cur_row[:Segment]
    @content_type = cur_row[:Content_Type]
    @rank = cur_row[:Rank]
    @location = cur_row[:Location]
    @notes = cur_row[:Notes]

    if total_count > cur_row_number
      sql = "WITH Cte AS (select Company_Domain, ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) AS number FROM #{@table} WHERE #{filter_type_query} AND #{filter_source_query}) SELECT * FROM Cte WHERE number = #{cur_row_number + 1}"
      @next_domain = @bigquery.query(sql).first[:Company_Domain]
    else
      @next_domain = ''
      @next_domain_source = ''
      flash[:alert] = 'No more sites'
    end

    return if cur_row[:Company_Domain].blank?

    #open uri
    begin
      logger.info 'open uri'
      response = open(to_url(@domain), {
                    allow_redirections: :all,
                    open_timeout: 5,
                    ssl_verify_mode: OpenSSL::SSL::VERIFY_NONE})
      @output = 'doc'
      @doc = Nokogiri::HTML.parse(response)
      # @doc.encoding = 'utf-8'
      @doc.to_html.gsub(/\.location\.replace\(.+\)/,'').gsub('replaceState','')
    rescue => error #Errno::ECONNREFUSED, Net::OpenTimeout, OpenSSL::SSL::SSLError, SocketError, OpenURI::HTTPError
      # begin
      #   logger.info 'make screenshot'
      #   @output = 'picture'
      #   screenshot = Gastly.screenshot(to_url(@domain), timeout: 5000)
      #   screenshot.phantomjs_options = '--ignore-ssl-errors=true'
      #   image = screenshot.capture
      #   image.save(Rails.root.join('public','site_screenshot.png'))
      # rescue
        @output = 'error'
        @output_error = "<div style='text-align: center;'>Can't load the website <a href='#{to_url(@domain)}' target='_blank'>#{@domain}</a><br>#{error.message}</div>"
      # end
    end
  end

  def filter_source
    current = CurrentState.first

    current.domain = nil
    current.filter_source = params[:filter_source].present? ? params[:filter_source] : nil
    current.filter_type = params[:filter_type].present? ? params[:filter_type] : 0
    current.save

    redirect_to root_path
  end

  def tagging
    current = CurrentState.first

    unless params[:skip]
      set_bq_vars
      # row = {
      #   :Source => params[:source],
      #   :Company_Domain => params[:domain],
      #   :Segment => params[:segment],
      #   :Content_Type => params[:content_type],
      #   :Rank => params[:rank],
      #   :Reviewed_Date => DateTime.now,
      #   :Location => params[:location],
      #   :Notes => params[:notes]
      # }

      # @bigquery.query "DELETE FROM #{@table.query_id} WHERE Source = '#{current.domain_source}' AND Company_Domain = '#{current.domain}'"
      # @table.insert row

      row = "Source = '#{params[:source]}', "\
            "Company_Domain = '#{params[:domain]}', "\
            "Segment = '#{params[:segment]}', "\
            "Content_Type = '#{params[:content_type]}', "\
            "Rank = '#{params[:rank]}', "\
            "Reviewed_Date = '#{DateTime.now}', "\
            "Location = '#{params[:location]}', "\
            "Notes = '#{params[:notes].gsub(/\r\n/,'\\r\\n')}'"

      @bigquery.query "UPDATE #{@table} SET #{row} WHERE Company_Domain = '#{current.domain}'"
    end

    current.update_attributes(
        domain: params[:next_domain]
      )

    redirect_to root_path
  end

  def report
    set_bq_vars

    sql = "SELECT Source, COUNT(*) FROM #{@table} GROUP BY Source"
    counts = @bigquery.query(sql)

    sql = "SELECT Source, COUNT(*) FROM #{@table} WHERE Reviewed_Date IS NULL GROUP BY Source"
    new_counts = @bigquery.query(sql)

    @lists = {}

    counts.each do |row|
      @lists[row[:Source]] ||= {}
      @lists[row[:Source]][:targets_count] = row[:f0_]
    end

    new_counts.each do |row|
      @lists[row[:Source]] ||= {}
      @lists[row[:Source]][:new_targets_count] = row[:f0_]
    end
  end

  def add_domains
    @sources = session[:sources] || []

    @added = params[:added] || []
    @duplicates = params[:duplicates] || []
  end

  def add_domains_form
    set_bq_vars

    domains = params[:domains].split(/\r\n|\r|\n/)
    duplicate = {}
    added = []
    duplicates = []

    sql = "SELECT Company_Domain FROM #{@table} WHERE Company_Domain IN (#{domains.map{|d|"'#{d}'"}.join(', ')})"
    matched_domains = @bigquery.query(sql).map { |d| d[:Company_Domain] }

    # @table.data.all.each do |row|
    #   duplicate[row[:Company_Domain]] = true if domains.include?(row[:Company_Domain])
    # end

    domains.each do |domain|
      duplicates << domain && next if matched_domains.include?(domain)

      row = {
        :Source => params[:source],
        :Company_Domain => domain
      }

      dataset = @bigquery.dataset ENV['manual_dataset']
      table = dataset.table ENV['manual_table']
      table.insert row
      added << domain
    end

    redirect_to add_domains_path(added: added, duplicates: duplicates)
  end

  private

    def set_bq_vars
      @bigquery = Google::Cloud::Bigquery.new
      @table = "#{ENV['manual_dataset']}.#{ENV['manual_table']}"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def to_url str
    'https://' + str unless str.match(/^(http:|https:)/)
  end
end

app/views/home/add_domains.html.erb
<div class="container py-4">
  <%= link_to 'Back', root_path, class: 'd-inline-block mb-4' %>

  <% if @added.any? %>
    <p>
      <%= pluralize @added.count, 'domain' %> was added
    </p>
  <% end %>

  <% if @duplicates.any? %>
    <p>
      <%= pluralize @duplicates.count, 'domain' %>
      <%=@duplicates.count == 1 ? 'is' : 'are' %>
      duplicate<%=@duplicates.count == 1 ? '' : 's' %>
      (<%= @duplicates.join(' ') %>)
    </p>
  <% end %>

  <h1 class="mb-4">Add Domains</h1>
  
  <%= form_tag '/add_domains_form' do %>
    <div class="row">
      <div class="col">
        <%= select_tag :source, options_for_select(@sources),
          include_blank: 'Select List',
          class: 'form-control chosen-select mb-4',
          required: true %>

        <%= label_tag :domains, 'Separate domains by newline' %>
        <%= text_area_tag :domains, nil, class: 'form-control mb-4', rows: 5, required: true %>

        <%= submit_tag 'Add Domains', class: 'btn btn-primary' %>
      </div>

      <div class="col">
      </div>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<div class="container py-3 pb-2">
  <div class="row">
    <div class="col-md-3 gray-border-right">
      <%= form_tag '/filter_source' do %>
        <div class="d-flex justify-content-between mb-1">
          <%= select_tag :filter_source, options_for_select(@sources, @filter_source),
            include_blank: 'Select List',
            class: 'form-control flex-fill chosen-select' %>
          <%= button_tag 'Load', class: 'btn btn-secondary ml-2' %>
        </div>
        <%= radio_button_tag :filter_type, :new_domains, @filter_type == 'new_domains' %>
        <%= label_tag :filter_type_new_domains, 'New', class: 'mr-2' %>
        <%= radio_button_tag :filter_type, :all_domains, @filter_type == 'all_domains' %>
        <%= label_tag :filter_type_all_domains, 'All' %>
      <% end %>
    </div>

    <div class="col-md-9">
      <%= form_tag '/tagging' do %>
        <div class="row">
          <div class="col">
            <%= select_tag :segment, options_for_select(@segments, @segment),
              include_blank: 'Segment',
              class: 'form-control' %>

            <div class="mt-2">
              <%= link_to 'Report', report_path, class: 'mr-3' %>
              <%= link_to 'Add Domains', add_domains_path %>
            </div>
          </div>

          <div class="col">
            <%= select_tag :content_type, options_for_select(@content_types, @content_type),
              include_blank: 'Content Type',
              class: 'form-control' %>
          </div>

          <div class="col" style="flex-grow: 0; white-space: nowrap;">
            <%= radio_button_tag :location, :us, @location == 'us' %>
            <%= label_tag :location_us, 'US', class: 'mb-0' %>
            <br>
            <%= radio_button_tag :location, :intl, @location == 'intl' %>
            <%= label_tag :location_intl, 'INTL', class: 'mb-0' %>
          </div>

          <div class="col">
            <div class="d-flex mb-2">
              <%= hidden_field_tag :next_domain, @next_domain %>
              <%= hidden_field_tag :source, @source %>
              <%= hidden_field_tag :notes, @notes %>
              <button class="btn btn-secondary mr-2"
                      type="button" 
                      data-toggle="modal"
                      data-target="#notesModal">Notes</button>
              <%= text_field_tag :domain, @domain, class: 'form-control', readonly: true %>
              <%= submit_tag "Skip", name: 'skip', 
                  class: 'btn btn-secondary ml-2' %>
            </div>

            <div class="d-flex justify-content-between" 
                 style="margin-left: -0.25rem; margin-right: -0.25rem">
              <%= submit_tag 'Junk', name: 'rank',
                class: "btn btn-sm btn-danger flex-fill mx-1 #{'active' if @rank == 'Junk'}" %>
              <%= submit_tag 'rD', name: 'rank',
                class: "btn btn-sm btn-warning flex-fill mx-1 #{'active' if @rank == 'rD'}" %>
              <%= submit_tag 'rC', name: 'rank',
                class: "btn btn-sm btn-lemon flex-fill mx-1 #{'active' if @rank == 'rC'}>" %>
              <%= submit_tag 'rB', name: 'rank',
                class: "btn btn-sm btn-lime flex-fill mx-1 #{'active' if @rank == 'rB'}" %>
              <%= submit_tag 'rA', name: 'rank',
                class: "btn btn-sm btn-success flex-fill mx-1 #{'active' if @rank == 'rA'}" %>
              <%= submit_tag 'rAA', name: 'rank',
                class: "btn btn-sm btn-success flex-fill mx-1 #{'active' if @rank == 'rAA'}" %>
              <%= submit_tag 'rAAA', name: 'rank',
                class: "btn btn-sm btn-success flex-fill mx-1 #{'active' if @rank == 'rAAA'}" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<% case @output %>
<% when 'doc' %>
  <iframe sandbox="allow-same-origin allow-scripts allow-popups allow-forms" srcdoc="<%= @doc %>" style="width:100%; height: calc(100% - 109px);" frameborder="0"></iframe>
<% when 'picture' %>
  <div>
    <img src="site_screenshot.png" alt="site screenshot">
  </div>
<% else %>
  <%= @output_error.html_safe %>
<% end %>

<div class="modal fade" id="notesModal" tabindex="-1" role="dialog" aria-labelledby="notesModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Notes</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="form-group">
          <%= text_area_tag :notes_field, @notes, class: 'form-control', rows: 10 %>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary" id="btn-notes">Save</button>
      </div>
    </div>
  </div>
</div>

app/views/home/report.html.erb
<div class="container py-4">
  <%= link_to 'Back', root_path, class: 'd-inline-block mb-4' %>
  <h1 class="mb-4">Report</h1>
  
  <table class="table">
    <thead>
      <tr>
        <th scope="col">List</th>
        <th scope="col"># of Targets</th>
        <th scope="col"># of New Targets</th>
      </tr>
    </thead>
    <tbody>
      <% @lists.each do |name, counts| %>
        <tr>
          <td><%= name %></td>
          <td><%= counts[:targets_count] %></td>
          <td><%= counts[:new_targets_count] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tagger</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="notice"><%= notice %></div>
    <div class="alert"><%= alert %></div>
    <%= yield %>
  </body>
</html>